db:
  Host: localhost
  Port: 3306
  User: root
  # Password: Dev@2018
  Password: 123456
  DBname: tokens
server:
  port: 9997

ETHPriceAPI : https://api.coinmarketcap.com/v1/ticker/ethereum/
RateURL : http://web.juhe.cn:8080/finance/exchange/rmbquot?key=f71073f053166aeda870ad0ffec1f724
ETHserver : 
  server : http://47.101.47.204
  # server : http://127.0.0.1
  port : 8545
  WEB3port : 9998
TokenPriceURL : https://api.yitaifang.com/index/tokenInfo/
